# Generated by Django 4.2.7 on 2023-12-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_column='name', max_length=50, null=True)),
                ('description', models.TextField(db_column='description', max_length=50, null=True)),
                ('price', models.TextField(db_column='price', max_length=50, null=True)),
                ('image', models.ImageField(db_column='image', max_length=50, null=True, upload_to='')),
            ],
        ),
    ]
