# Generated by Django 4.2.7 on 2023-12-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothadmin', '0002_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', max_length=50, null=True)),
                ('staffid', models.TextField(db_column='description', max_length=50, null=True)),
                ('password', models.TextField(db_column='price', max_length=50, null=True)),
            ],
        ),
    ]
