# Generated by Django 4.2.7 on 2023-12-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', null=True)),
                ('dob', models.TextField(db_column='dob', null=True)),
                ('mob', models.TextField(db_column='mob', null=True)),
                ('state', models.TextField(db_column='state', null=True)),
                ('address', models.TextField(db_column='address', null=True)),
                ('pincode', models.TextField(db_column='pincode', null=True)),
                ('landmark', models.TextField(db_column='landmark', null=True)),
                ('email', models.TextField(db_column='email', null=True)),
                ('p1', models.TextField(db_column='p1', null=True)),
                ('p2', models.TextField(db_column='p2', null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
