# Generated by Django 4.2.7 on 2023-12-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='p2',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.TextField(db_column='password', null=True),
        ),
    ]
