# Generated by Django 4.2.7 on 2024-01-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothapp', '0004_alter_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', max_length=200, null=True)),
                ('email', models.TextField(db_column='email', max_length=200, null=True)),
                ('message', models.TextField(db_column='message', max_length=200, null=True)),
            ],
        ),
    ]
